import turtle as t

def apeach():
       t.shape("turtle")
       t.speed(5)
       t.pencolor("#fdab9f")
       t.width(5)
       t.penup()
       t.setposition(7,200)
       t.pendown()
       t.fillcolor("#ffe6ee")
       t.begin_fill()
       t.right(20)
       t.circle(-300,30)
       t.circle(-100,100)
       t.circle(-200,35)
       t.circle(-900,5)
       t.circle(-100,70)
       t.right(10)
       t.circle(-150,60)
       t.fd(60)
       t.left(10)
       t.fd(40)
       t.setposition(7,200)
       t.end_fill()
       t.penup()
       t.pencolor("#581845")
       t.setposition(-56,70)
       t.pendown()
       t.fillcolor("#581845")
       t.begin_fill()
       t.circle(-8)
       t.end_fill()
       t.penup()
       t.setposition(44,70)
       t.pendown()
       t.fillcolor("#581845")
       t.begin_fill()
       t.circle(-8)
       t.end_fill()
       t.penup()
       t.pencolor("#FFB6C1")
       t.fillcolor("#FFB6C1")
       t.setposition(-125,0)
       t.pendown()
       t.begin_fill()
       t.seth(-45)
       t.circle(40,90)
       t.circle(20,90)
       t.circle(40,90)
       t.circle(20,90)
       t.end_fill()
       t.penup()
       t.setposition(65,2)
       t.pendown()
       t.begin_fill()
       t.seth(-45)
       t.circle(40,90)
       t.circle(20,90)
       t.circle(40,90)
       t.circle(20,90)
       t.end_fill()
       t.penup()
       t.setposition(-40,0)
       t.pendown()
       t.fillcolor("#EE918D")
       t.pencolor("#900A22")
       t.begin_fill()
       t.seth(-45)
       t.circle(60,90)
       t.circle(20,90)
       t.left(45)
       t.fd(76)
       t.left(20)
       t.circle(20,95)
       t.end_fill()
       t.penup()
       t.pencolor("#ffffff")
       t.fillcolor("#ffffff")
       t.begin_fill()
       t.setposition(-10,23)
       t.pendown()
       t.setposition(-7,15)
       t.setposition(10,15)
       t.setposition(13,23)
       t.goto(-10,23)
       t.end_fill()
       t.hideturtle()
       t.exitonclick()

def lion():
       t.shape("turtle")
       t.speed(5)
       t.pencolor("#000000")
       t.width(10)
       t.penup()
       t.setposition(0,100)
       t.pendown()
       t.circle(-170,30)
       t.right(90)
       t.fillcolor("#ffaf00")
       t.begin_fill()
       t.circle(60)
       t.end_fill()
       t.left(90)
       t.circle(-170,300)
       t.left(90)
       t.fillcolor("#ffaf00")
       t.begin_fill()
       t.circle(60)
       t.end_fill()
       t.right(90)
       t.circle(-170,30)
       t.fillcolor("#ffaf00")
       t.begin_fill()
       t.circle(-170)
       t.end_fill()
       t.penup()
       t.setposition(-100,7)
       t.width(15)
       t.pendown()
       t.fd(60)
       t.penup()
       t.setposition(50,7)
       t.pendown()
       t.fd(60)
       t.width(10)
       t.penup()
       t.setposition(0,-75)
       t.fillcolor("#fff0f0")
       t.pendown()
       t.begin_fill()
       t.left(70)
       t.circle(-25,310)
       t.left(115)
       t.circle(-25,310)
       t.end_fill()
       t.circle(-1)
       t.penup()
       t.setposition(-78,-35)
       t.pendown()
       t.circle(5)
       t.penup()
       t.setposition(78,-35)
       t.pendown()
       t.circle(5)
       t.penup()
       t.setposition(300,300)
       t.exitonclick()

def bonobono():
       t.shape("turtle")
       t.speed(5)
       t.pencolor("#000000")
       t.width(5)
       t.penup()
       t.setposition(0,140)
       t.pendown()
       t.fillcolor("#9de4ff")
       t.begin_fill()
       t.circle(-200)
       t.end_fill()
       t.penup()
       t.setposition(-150,-18)
       t.pendown()
       t.width(15)
       t.circle(4)
       t.penup()
       t.setposition(150,-18)
       t.pendown()
       t.circle(4)

       t.penup()
       t.setposition(0,-90)
       t.width(26)
       t.pendown()
       t.circle(14)
       t.width(7)
       t.penup()
       t.setposition(14.5,-90)
       t.pendown()
       t.fillcolor("#fff0f0")
       t.begin_fill()
       t.left(60)
       t.circle(-30,150)
       t.penup()
       t.setposition(14.5,-90)
       t.pendown()
       t.circle(30,150)
       t.end_fill()

       t.penup()
       t.setposition(-14.5,-90)
       t.pendown()
       t.left(200)
       t.fillcolor("#fff0f0")
       t.begin_fill()
       t.circle(-30,150)
       t.penup()
       t.setposition(-14.5,-90)
       t.pendown()
       t.circle(30,150)
       t.right(200)
       t.end_fill()


       t.penup()
       t.setposition(63,-98)
       t.right(60)
       t.pendown()
       t.forward(40)

       t.penup()
       t.setposition(58,-98)
       t.left(30)
       t.pendown()
       t.forward(40)
       t.right(30)

       t.penup()
       t.setposition(58,-98)
       t.right(30)
       t.pendown()
       t.forward(40)
       t.left(30)

       t.penup()
       t.setposition(-63,-98)
       t.pendown()
       t.forward(-40)

       t.penup()
       t.setposition(-58,-98)
       t.left(30)
       t.pendown()
       t.forward(-40)
       t.right(30)

       t.penup()
       t.setposition(-58,-98)
       t.right(30)
       t.pendown()
       t.forward(-40)
       t.left(30)

       t.hideturtle()
            
       t.exitonclick()
    


    
    
    

print("그림 그려주는 프로그램에 오신것을 환영합니다! \n")
print("보기: 1. 어피치 2. 라이언 3. 보노보노 \n")
num = int(input("보기 중 그리고 싶으신 그림의 번호를 입력하세요: \n"))

if num == 1:
    apeach()

elif num == 2:
    lion()

else:
    bonobono()
